### ISSUE TITLE
Make fresh install usable

### ISSUE THREAD

**Issue by polyedre** [dubicube/tobrie#2]
While trying to use the bot, I faced some problems with code that is not present in the repo.

In config.py, there are a lot of file paths:

```
tempPath = '../temp/'
soundPath = '../sound/'
memePath = '../meme/'
logPath = '../log/'
tempPath = '../temp/'
mapPath = '../maps/'
stickers_map_file = '../maps/sticker_map'
text_map_file = '../maps/text_map'
video_map_file = '../maps/video_map'
conv_config_path = '../data/'
``` 

Can you add a default file structure in this repo and default maps file ?

**Comment by dubicube** [comment]
Basic ressource files have been added, and README has been updated to clarify how to use the bot.
The bot can now start just with the file structure in the repo (just adding the tokens file).
